export const AGENDA = [
  {
    name: "Code Relay(Team)",
    start: "10:30 AM",
    end: "11:30 AM",
    venue: "AI Laboratory",
  },
  {
    name: "Whispering Images (Team)",
    start: "10:30 AM",
    end: "01:30 PM",
    venue: "Hi - Tech hall",
  },
  {
    name: "Code Gulf (Solo)",
    start: "10:30 AM",
    end: "11:30 AM",
    venue: "DS Wing",
  },
  {
    name: "Murder Mystery (Team)",
    start: "11:00 AM",
    end: "02:00 PM",
    venue: "Civil Block CR",
  },
  {
    name: "Sherlock Code (Team)",
    start: "11:30 AM",
    end: "01:00 PM",
    venue: "Both Wings",
  },
  {
    name: "Paper Presentation (Team)",
    start: "11:30 AM",
    end: "02:30 PM",
    venue: "Hi - Tech hall",
  },
  {
    name: "Kollywood Trivia (Team)",
    start: "11:30 AM",
    end: "01:30 PM",
    venue: "Civil Block CR",
  },
  {
    name: "Solo Singing (Solo)",
    start: "11:30 AM",
    end: "02:00 PM",
    venue: "Civil Block CR",
  },
  {
    name: "Green Screen (Team)",
    start: "12:00 AM",
    end: "02:00 PM",
    venue: "Civil Block CR",
  },
  {
    name: "Switch Saga (Team)",
    start: "01:00 PM",
    end: "02:30 PM",
    venue: "Civil Block CR",
  },
  {
    name: "Tech Startup (Team)",
    start: "01:00 PM",
    end: "02:30 PM",
    venue: "Civil Block CR",
  },
  {
    name: "Adaptunes (Solo)",
    start: "02:00 PM",
    end: "03:15 PM",
    venue: "OAT",
  },
  { name: "Sponsor Slot", start: "03:15 PM", end: "03:25 PM", venue: "OAT" },
  {
    name: "Prize Distribution",
    start: "03:25 PM",
    end: "04:00 PM",
    venue: "OAT",
  },
  { name: "DJ", start: "04:00 PM", end: "04:45 PM", venue: "OAT" },
];
