export enum EVENT_TYPE {
  TECH,
  NONTECH,
  ONLINE,
}

export enum EVENT_MODE {
  OFFLINE,
  ONLINE,
}

export enum EVENT_COUNT {
  PER_HEAD,
  PER_TEAM,
}

export enum EVENT_ID {
  SHERLOCK_CODE,
  SCHEMER,
  BLIND_PRESENTATION,
  THAT_ESCALATED_QUICKLY,
  PAPER_PRESENTATION,
  SIGMA,
  THE_WEB_SLASHER,
  ADAPT_TUNES,
  QUIZ_IN_KOLLYWOOD,
  BOX_CRICKET,
  IMPROV,
  FUTSAL,
  TUG_OF_WAR,
  SOLO_SINGING,
  VALORANT,
  REELS,
  VIDEO_EDITING,
  ART_OF_APERTURE,
}

export enum UPI_ID {
  ASVIN = "asvinbaskar@okhdfcbank",
  JENNIFER = "jennifersharon07@oksbi",
  DEEPAK = "deepakat274@okhdfcbank",
  NAVEEN = "snaveenkumar343@okhdfcbank",
  SABETHA = "aisabetha05@okaxis",
}

export const EVENTS = [
  {
    name: "Sherlock Code",
    type: EVENT_TYPE.TECH,
    mode: EVENT_MODE.OFFLINE,
    count: EVENT_COUNT.PER_TEAM,
    pay: UPI_ID.JENNIFER,
    fee: 60,
    minTeam: 1,
    maxTeam: 2,
    whatsapp: "https://chat.whatsapp.com/LVYMKGrBDsTJXRp7KC0YPo",
  },
  {
    name: "Schemer",
    type: EVENT_TYPE.TECH,
    mode: EVENT_MODE.OFFLINE,
    count: EVENT_COUNT.PER_TEAM,
    pay: UPI_ID.ASVIN,
    fee: 120,
    minTeam: 1,
    maxTeam: 3,
    whatsapp: "https://chat.whatsapp.com/C337dqlVyVDHldLUJC0PSF",
  },
  {
    name: "Blind Presentation",
    type: EVENT_TYPE.TECH,
    mode: EVENT_MODE.OFFLINE,
    count: EVENT_COUNT.PER_TEAM,
    pay: UPI_ID.DEEPAK,
    fee: 90,
    minTeam: 1,
    maxTeam: 4,
    whatsapp: "https://chat.whatsapp.com/GmY56xz2R7B9ag2kuWwyWm",
  },
  {
    name: "That Escalated Quickly",
    type: EVENT_TYPE.TECH,
    mode: EVENT_MODE.OFFLINE,
    count: EVENT_COUNT.PER_TEAM,
    pay: UPI_ID.NAVEEN,
    fee: 90,
    minTeam: 2,
    maxTeam: 3,
    whatsapp: "https://chat.whatsapp.com/K9hq9cSzPKHGBAaHCzLn4V",
  },
  {
    name: "Paper Presentation",
    type: EVENT_TYPE.TECH,
    mode: EVENT_MODE.OFFLINE,
    count: EVENT_COUNT.PER_TEAM,
    pay: UPI_ID.JENNIFER,
    fee: 180,
    minTeam: 1,
    maxTeam: 4,
    whatsapp: "https://chat.whatsapp.com/DEoLBKoPBqdIZSmPA47R81",
  },
  {
    name: "Sigma",
    type: EVENT_TYPE.TECH,
    mode: EVENT_MODE.OFFLINE,
    count: EVENT_COUNT.PER_HEAD,
    pay: UPI_ID.DEEPAK,
    fee: 50,
    minTeam: 1,
    maxTeam: 1,
    whatsapp: "https://chat.whatsapp.com/C9Y5ag5aFwCFJxHP50uWj4",
  },
  {
    name: "The Web Slasher",
    type: EVENT_TYPE.TECH,
    mode: EVENT_MODE.ONLINE,
    count: EVENT_COUNT.PER_HEAD,
    pay: UPI_ID.NAVEEN,
    fee: 50,
    minTeam: 1,
    maxTeam: 1,
    whatsapp: "https://chat.whatsapp.com/IR4WM3RMfV47KsxiclA9ji",
  },
  {
    name: "Adapt Tunes",
    type: EVENT_TYPE.NONTECH,
    mode: EVENT_MODE.OFFLINE,
    count: EVENT_COUNT.PER_HEAD,
    pay: UPI_ID.ASVIN,
    fee: 50,
    minTeam: 1,
    maxTeam: 1,
    whatsapp: "https://chat.whatsapp.com/DEZVfXvD4sa0neqcplTG7L",
  },
  {
    name: "Quiz in Kollywood",
    type: EVENT_TYPE.NONTECH,
    mode: EVENT_MODE.OFFLINE,
    count: EVENT_COUNT.PER_TEAM,
    pay: UPI_ID.ASVIN,
    fee: 100,
    minTeam: 1,
    maxTeam: 4,
    whatsapp: "https://chat.whatsapp.com/DRHcgimVkRhHsSdI9nT1CN",
  },
  {
    name: "Murder Mystery",
    type: EVENT_TYPE.NONTECH,
    mode: EVENT_MODE.OFFLINE,
    count: EVENT_COUNT.PER_TEAM,
    pay: UPI_ID.NAVEEN,
    fee: 120,
    minTeam: 1,
    maxTeam: 4,
    whatsapp: "https://chat.whatsapp.com/HPJvOPgCuu3EdiYZmXuCsk",
  },
  {
    name: "Box Cricket",
    type: EVENT_TYPE.NONTECH,
    mode: EVENT_MODE.OFFLINE,
    count: EVENT_COUNT.PER_TEAM,
    pay: UPI_ID.JENNIFER,
    fee: 200,
    minTeam: 5,
    maxTeam: 7,
    whatsapp: "https://chat.whatsapp.com/Jza0fXHRENnHp0J7xoJi53",
  },
  {
    name: "Improv",
    type: EVENT_TYPE.NONTECH,
    mode: EVENT_MODE.OFFLINE,
    count: EVENT_COUNT.PER_TEAM,
    pay: UPI_ID.SABETHA,
    fee: 50,
    minTeam: 1,
    maxTeam: 1,
    whatsapp: "https://chat.whatsapp.com/IzycdeH0NvqAJZwExVFPE1",
  },
  {
    name: "Futsal",
    type: EVENT_TYPE.NONTECH,
    mode: EVENT_MODE.OFFLINE,
    count: EVENT_COUNT.PER_TEAM,
    pay: UPI_ID.DEEPAK,
    fee: 300,
    minTeam: 4,
    maxTeam: 6,
    whatsapp: "https://chat.whatsapp.com/LsnFraLMVZUKwceiuyQnNM",
  },
  {
    name: "Solo Singing",
    type: EVENT_TYPE.NONTECH,
    mode: EVENT_MODE.OFFLINE,
    count: EVENT_COUNT.PER_TEAM,
    pay: UPI_ID.JENNIFER,
    fee: 50,
    minTeam: 1,
    maxTeam: 1,
    whatsapp: "https://chat.whatsapp.com/B5b4aIIxruwJk4RqDsLPcO",
  },
  {
    name: "Valorant",
    type: EVENT_TYPE.NONTECH,
    mode: EVENT_MODE.OFFLINE,
    count: EVENT_COUNT.PER_TEAM,
    pay: UPI_ID.ASVIN,
    fee: 200,
    minTeam: 5,
    maxTeam: 5,
    whatsapp: "https://chat.whatsapp.com/HjhekCw89OnDnYnAHEX6fm",
  },
  {
    name: "Reels",
    type: EVENT_TYPE.NONTECH,
    mode: EVENT_MODE.OFFLINE,
    count: EVENT_COUNT.PER_HEAD,
    pay: UPI_ID.DEEPAK,
    fee: 30,
    minTeam: 1,
    maxTeam: 1,
    whatsapp: "https://chat.whatsapp.com/LWg7o1mksfqArZ6K0ZWma7",
  },
  {
    name: "Video Editing",
    type: EVENT_TYPE.NONTECH,
    mode: EVENT_MODE.OFFLINE,
    count: EVENT_COUNT.PER_HEAD,
    pay: UPI_ID.NAVEEN,
    fee: 30,
    minTeam: 1,
    maxTeam: 1,
    whatsapp: "https://chat.whatsapp.com/JV0uOQkAs59118pBgGfJ1r",
  },
  {
    name: "Art of Aperture",
    type: EVENT_TYPE.NONTECH,
    mode: EVENT_MODE.OFFLINE,
    count: EVENT_COUNT.PER_HEAD,
    pay: UPI_ID.SABETHA,
    fee: 30,
    minTeam: 1,
    maxTeam: 1,
    whatsapp: "https://chat.whatsapp.com/HqTkyHLAUX1B2057PR2PJZ",
  },
];
