export enum EVENT_TYPE {
  TECH,
  NONTECH,
  ONLINE,
}

export enum EVENT_MODE {
  OFFLINE,
  ONLINE,
}

export enum EVENT_COUNT {
  PER_HEAD,
  PER_TEAM,
}

export const EVENTS = [
  {
    name: "Sherlock Code",
    type: EVENT_TYPE.TECH,
    mode: EVENT_MODE.OFFLINE,
    count: EVENT_COUNT.PER_HEAD,
    fee: 60,
    minTeam: 1,
    maxTeam: 2,
  },
  {
    name: "Schemer",
    type: EVENT_TYPE.TECH,
    mode: EVENT_MODE.OFFLINE,
    count: EVENT_COUNT.PER_HEAD,
    fee: 120,
    minTeam: 1,
    maxTeam: 3,
  },
  {
    name: "Blind Presentation",
    type: EVENT_TYPE.TECH,
    mode: EVENT_MODE.OFFLINE,
    count: EVENT_COUNT.PER_HEAD,
    fee: 90,
    minTeam: 1,
    maxTeam: 4,
  },
  {
    name: "That Escalated Quickly",
    type: EVENT_TYPE.TECH,
    mode: EVENT_MODE.OFFLINE,
    count: EVENT_COUNT.PER_HEAD,
    fee: 90,
    minTeam: 2,
    maxTeam: 3,
  },
  {
    name: "Paper Presentation",
    type: EVENT_TYPE.TECH,
    mode: EVENT_MODE.OFFLINE,
    count: EVENT_COUNT.PER_HEAD,
    fee: 180,
    minTeam: 1,
    maxTeam: 1,
  },
  {
    name: "Sigma",
    type: EVENT_TYPE.TECH,
    mode: EVENT_MODE.OFFLINE,
    count: EVENT_COUNT.PER_HEAD,
    fee: 50,
    minTeam: 1,
    maxTeam: 1,
  },
  {
    name: "The Web Slasher",
    type: EVENT_TYPE.TECH,
    mode: EVENT_MODE.ONLINE,
    count: EVENT_COUNT.PER_HEAD,
    fee: 50,
    minTeam: 1,
    maxTeam: 1,
  },
  {
    name: "Adapt Tunes",
    type: EVENT_TYPE.NONTECH,
    mode: EVENT_MODE.OFFLINE,
    count: EVENT_COUNT.PER_HEAD,
    fee: 100,
    minTeam: 1,
    maxTeam: 1,
  },
  {
    name: "Quiz in Kollywood",
    type: EVENT_TYPE.NONTECH,
    mode: EVENT_MODE.OFFLINE,
    count: EVENT_COUNT.PER_HEAD,
    fee: 100,
    minTeam: 1,
    maxTeam: 4,
  },
  {
    name: "Box Cricket",
    type: EVENT_TYPE.NONTECH,
    mode: EVENT_MODE.OFFLINE,
    count: EVENT_COUNT.PER_HEAD,
    fee: 200,
    minTeam: 5,
    maxTeam: 7,
  },
  {
    name: "Improv",
    type: EVENT_TYPE.NONTECH,
    mode: EVENT_MODE.OFFLINE,
    count: EVENT_COUNT.PER_HEAD,
    fee: 50,
    minTeam: 1,
    maxTeam: 1,
  },
  {
    name: "Futsal",
    type: EVENT_TYPE.NONTECH,
    mode: EVENT_MODE.OFFLINE,
    count: EVENT_COUNT.PER_HEAD,
    fee: 300,
    minTeam: 4,
    maxTeam: 6,
  },
  {
    name: "Tug of War",
    type: EVENT_TYPE.NONTECH,
    mode: EVENT_MODE.OFFLINE,
    count: EVENT_COUNT.PER_HEAD,
    fee: 100,
    minTeam: 5,
    maxTeam: 5,
  },
  {
    name: "Solo Singing",
    type: EVENT_TYPE.NONTECH,
    mode: EVENT_MODE.OFFLINE,
    count: EVENT_COUNT.PER_HEAD,
    fee: 50,
    minTeam: 1,
    maxTeam: 1,
  },
  {
    name: "Valorant",
    type: EVENT_TYPE.NONTECH,
    mode: EVENT_MODE.OFFLINE,
    count: EVENT_COUNT.PER_TEAM,
    fee: 200,
    minTeam: 5,
    maxTeam: 5,
  },
  {
    name: "Reels",
    type: EVENT_TYPE.NONTECH,
    mode: EVENT_MODE.OFFLINE,
    count: EVENT_COUNT.PER_HEAD,
    fee: 30,
    minTeam: 1,
    maxTeam: 1,
  },
  {
    name: "Video Editing",
    type: EVENT_TYPE.NONTECH,
    mode: EVENT_MODE.OFFLINE,
    count: EVENT_COUNT.PER_HEAD,
    fee: 30,
    minTeam: 1,
    maxTeam: 1,
  },
  {
    name: "Art of Aperture",
    type: EVENT_TYPE.NONTECH,
    mode: EVENT_MODE.OFFLINE,
    count: EVENT_COUNT.PER_HEAD,
    fee: 30,
    minTeam: 1,
    maxTeam: 1,
  },
];
